[package]
name = "gcfuse-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
fuser = "0.16.0"
gcn_disk = "0.3.1"
libc = "0.2.180"
rvz = "0.2.1"
